//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Datenbank01Entities : DbContext
    {
        public Datenbank01Entities()
            : base("name=Datenbank01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<F_ANALYSIS> F_ANALYSIS { get; set; }
        public virtual DbSet<AppComponentParameter> AppComponentParameters { get; set; }
        public virtual DbSet<AppComponentParameterValue> AppComponentParameterValues { get; set; }
        public virtual DbSet<D_Apps> D_Apps { get; set; }
        public virtual DbSet<DataBaseWatcher> DataBaseWatchers { get; set; }
        public virtual DbSet<FlowControl> FlowControls { get; set; }
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }
        public virtual DbSet<D_Analysis> D_Analysis { get; set; }
        public virtual DbSet<D_Signal> D_Signal { get; set; }
        public virtual DbSet<D_SYMBOL> D_SYMBOL { get; set; }
        public virtual DbSet<D_USER_ACCOUNTS> D_USER_ACCOUNTS { get; set; }
        public virtual DbSet<D_UserDepot> D_UserDepot { get; set; }
        public virtual DbSet<F_AnalysisData> F_AnalysisData { get; set; }
        public virtual DbSet<F_DepotComponents> F_DepotComponents { get; set; }
        public virtual DbSet<F_SignalData> F_SignalData { get; set; }
        public virtual DbSet<F_SymbolData> F_SymbolData { get; set; }
        public virtual DbSet<F_UserDepot> F_UserDepot { get; set; }
        public virtual DbSet<GamePlay> GamePlays { get; set; }
        public virtual DbSet<S_SYMBOL_REFERENCE_DATA_FIGI> S_SYMBOL_REFERENCE_DATA_FIGI { get; set; }
        public virtual DbSet<S_MARKET_DATA_STREAM> S_MARKET_DATA_STREAM { get; set; }
        public virtual DbSet<D_SYMBOL1> D_SYMBOL1 { get; set; }
        public virtual DbSet<F_SYMBOL> F_SYMBOL { get; set; }
        public virtual DbSet<F_MARKET_DATA1> F_MARKET_DATA1 { get; set; }
        public virtual DbSet<F_PORTFOLIO> F_PORTFOLIO { get; set; }
        public virtual DbSet<F_SYMBOL_REFERENCE_DATA_FIGI> F_SYMBOL_REFERENCE_DATA_FIGI { get; set; }
        public virtual DbSet<D_ItemMain> D_ItemMain { get; set; }
        public virtual DbSet<F_ItemMain> F_ItemMain { get; set; }
        public virtual DbSet<F_API_TRIGGER> F_API_TRIGGER { get; set; }
        public virtual DbSet<IEXCloudClass> IEXCloudClasses { get; set; }
        public virtual DbSet<IEXCloudCompany> IEXCloudCompanies { get; set; }
        public virtual DbSet<IEXCloudHistoric> IEXCloudHistorics { get; set; }
        public virtual DbSet<IEXCloudSymbolList> IEXCloudSymbolLists { get; set; }
        public virtual DbSet<TmpTable> TmpTables { get; set; }
        public virtual DbSet<F_Market_Data> F_Market_Data { get; set; }
        public virtual DbSet<MarketValue> MarketValues { get; set; }
        public virtual DbSet<F_SYMBOL_NEWS> F_SYMBOL_NEWS { get; set; }
        public virtual DbSet<D_BLOOMBERG_EXCHANGE> D_BLOOMBERG_EXCHANGE { get; set; }
        public virtual DbSet<F_BbExchangeToName> F_BbExchangeToName { get; set; }
        public virtual DbSet<F_DIVIDENDS> F_DIVIDENDS { get; set; }
        public virtual DbSet<F_USER_ACCOUNTS> F_USER_ACCOUNTS { get; set; }
        public virtual DbSet<TEMP_VIEW> TEMP_VIEW { get; set; }
        public virtual DbSet<V_DATA_FOR_ANALYSIS> V_DATA_FOR_ANALYSIS { get; set; }
        public virtual DbSet<V_DepotComponentsAggregated> V_DepotComponentsAggregated { get; set; }
        public virtual DbSet<V_DepotComponentsDetail> V_DepotComponentsDetail { get; set; }
        public virtual DbSet<V_MARKET_DATA_CLOSE_INTRADAY> V_MARKET_DATA_CLOSE_INTRADAY { get; set; }
        public virtual DbSet<V_MARKET_DATA_EOD> V_MARKET_DATA_EOD { get; set; }
        public virtual DbSet<View_FlowControl> View_FlowControl { get; set; }
        public virtual DbSet<V_RUNNING_QUERIES> V_RUNNING_QUERIES { get; set; }
        public virtual DbSet<V_F_SYMBOL_TO_API> V_F_SYMBOL_TO_API { get; set; }
        public virtual DbSet<V_SYMBOL> V_SYMBOL { get; set; }
        public virtual DbSet<V_UserDepot> V_UserDepot { get; set; }
        public virtual DbSet<V_UserDepotAnalytics> V_UserDepotAnalytics { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<V_LATEST_MARKET_DATA> V_LATEST_MARKET_DATA { get; set; }
    
        public virtual int S_Open_Figi_To_Prod()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("S_Open_Figi_To_Prod");
        }
    
        public virtual int S_TRANSFORM_ALPHA_ADVANTAGE_CA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("S_TRANSFORM_ALPHA_ADVANTAGE_CA");
        }
    
        public virtual int S_TRANSFORM_ALPHA_ADVANTAGE_MaDa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("S_TRANSFORM_ALPHA_ADVANTAGE_MaDa");
        }
    
        public virtual int S_TRANSFORM_FMP_MaDa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("S_TRANSFORM_FMP_MaDa");
        }
    
        public virtual int S_Transform_SymbolData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("S_Transform_SymbolData");
        }
    
        public virtual int SP_IMPORT_TO_SYMBOL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_IMPORT_TO_SYMBOL");
        }
    
        public virtual int SP_IMPORT_TO_SYMBOL_NEWS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_IMPORT_TO_SYMBOL_NEWS");
        }
    }
}
