//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_BLOOMBERG_EXCHANGE
    {
        public int BbExchangeID { get; set; }
        public string BbExchangeCode { get; set; }
        public System.DateTime VALID_FROM { get; set; }
        public System.DateTime VALID_TO { get; set; }
        public Nullable<System.DateTime> ITS { get; set; }
        public Nullable<System.DateTime> UTS { get; set; }
    }
}
