//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataBaseWatcher
    {
        public int WatchId { get; set; }
        public string TableNameSource { get; set; }
        public string TableNameTarget { get; set; }
        public string ColumnNamesSource { get; set; }
        public string ColumnNamesTarget { get; set; }
        public string FilterSource { get; set; }
        public string FilterTarget { get; set; }
        public string AggregationInterval { get; set; }
        public Nullable<int> AppID { get; set; }
        public string AppName { get; set; }
        public string Parameter { get; set; }
        public string SourceTable1 { get; set; }
        public string TargetTable1 { get; set; }
        public Nullable<System.DateTime> TaskPlanned { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public System.DateTime ITS { get; set; }
        public System.DateTime UTS { get; set; }
        public string Status { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> AnalysisId { get; set; }
        public Nullable<int> UniqueIdentifier { get; set; }
        public string UniqueColumnName { get; set; }
        public string SourceTableGroupe { get; set; }
        public string TargetTableGroupe { get; set; }
    }
}
