//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_DIVIDENDS
    {
        public string SYMBOL { get; set; }
        public Nullable<decimal> CASH_VALUE { get; set; }
        public string CASH_CURRENCY { get; set; }
        public Nullable<System.DateTime> ITS { get; set; }
        public Nullable<System.DateTime> UTS { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public int ColumnID { get; set; }
    }
}
