//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_ItemMain
    {
        public int ItemMainId { get; set; }
        public string ItemMainName { get; set; }
        public string UserHK { get; set; }
        public string ItemMainImagePath { get; set; }
        public byte[] ItemMainImage { get; set; }
        public string ItemMainTitle { get; set; }
        public string ItemMainDescription { get; set; }
        public string Status { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public Nullable<System.DateTime> ITS { get; set; }
        public Nullable<System.DateTime> UTS { get; set; }
    }
}
