//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_Market_Data
    {
        public int id { get; set; }
        public string symbol { get; set; }
        public string date { get; set; }
        public string minute { get; set; }
        public Nullable<decimal> open { get; set; }
        public Nullable<decimal> high { get; set; }
        public Nullable<decimal> low { get; set; }
        public Nullable<decimal> close { get; set; }
        public Nullable<int> volume { get; set; }
        public Nullable<decimal> marketOpen { get; set; }
        public Nullable<decimal> marketClose { get; set; }
        public Nullable<decimal> marketHigh { get; set; }
        public Nullable<decimal> marketLow { get; set; }
        public Nullable<decimal> marketAverage { get; set; }
        public Nullable<int> marketVolume { get; set; }
        public Nullable<decimal> marketNotional { get; set; }
        public Nullable<int> marketNumberOfTrades { get; set; }
        public Nullable<decimal> marketChangeOverTime { get; set; }
        public Nullable<decimal> notional { get; set; }
        public Nullable<int> numberOfTrades { get; set; }
        public Nullable<decimal> changeOverTime { get; set; }
        public Nullable<decimal> unadjOpen { get; set; }
        public Nullable<decimal> unadjHigh { get; set; }
        public Nullable<decimal> unadjLow { get; set; }
        public Nullable<decimal> unadjClose { get; set; }
        public Nullable<int> unadjVolume { get; set; }
        public Nullable<decimal> change { get; set; }
        public Nullable<decimal> changePercent { get; set; }
    }
}
