//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_PORTFOLIO
    {
        public int USER_ID { get; set; }
        public int COLUMN_ID { get; set; }
        public Nullable<int> AMOUNT { get; set; }
    }
}
