//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_SymbolData
    {
        public int SymbolId { get; set; }
        public string CompanyName { get; set; }
        public string Sector { get; set; }
        public string Ceo { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string Website { get; set; }
        public string Industry { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public Nullable<System.DateTime> ITS { get; set; }
        public Nullable<System.DateTime> UTS { get; set; }
    }
}
