//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_SYMBOL_REFERENCE_DATA_FIGI
    {
        public int ColumnID { get; set; }
        public string isin { get; set; }
        public string figi { get; set; }
        public string name { get; set; }
        public string ticker { get; set; }
        public string exchCode { get; set; }
        public string compositeFIGI { get; set; }
        public string uniqueID { get; set; }
        public string securityType { get; set; }
        public string marketSector { get; set; }
        public string shareClassFIGI { get; set; }
        public string uniqueIDFutOpt { get; set; }
        public string securityType2 { get; set; }
        public string securityDescription { get; set; }
        public Nullable<System.DateTime> ITS { get; set; }
        public Nullable<System.DateTime> UTS { get; set; }
    }
}
