//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowControl
    {
        public int FlowID { get; set; }
        public Nullable<int> AppID { get; set; }
        public string AppName { get; set; }
        public string Parameter { get; set; }
        public string SourceTable1 { get; set; }
        public string SourceTable2 { get; set; }
        public string TargetTable1 { get; set; }
        public string TargetTable2 { get; set; }
        public Nullable<int> TaskSuccess { get; set; }
        public Nullable<System.DateTime> TaskPlanned { get; set; }
        public Nullable<int> WatchId { get; set; }
        public Nullable<int> AnalysisId { get; set; }
    }
}
