//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePlay
    {
        public string Id { get; set; }
        public string Fighter { get; set; }
        public string PageLast { get; set; }
        public string FirstRiddle1 { get; set; }
        public string FirstRiddle2 { get; set; }
        public string FirstRiddle3 { get; set; }
        public string FirstRiddle4 { get; set; }
        public string FirstRiddle5 { get; set; }
        public string FirstRiddle6 { get; set; }
        public string FirstRiddle7 { get; set; }
        public string FirstRiddle8 { get; set; }
        public string FirstRiddle9 { get; set; }
        public string FirstRiddle10 { get; set; }
        public string FirstRiddle11 { get; set; }
        public string FirstRiddle12 { get; set; }
        public string FirstRiddle13 { get; set; }
        public string FirstRiddle14 { get; set; }
        public string FirstRiddle15 { get; set; }
        public string FirstRiddle16 { get; set; }
    }
}
