//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEXCloudSymbolList
    {
        public int Id { get; set; }
        public string symbol { get; set; }
        public string name { get; set; }
        public string date { get; set; }
        public string type { get; set; }
        public string iexId { get; set; }
        public string region { get; set; }
        public string currency { get; set; }
        public string isEnabled { get; set; }
        public string figi { get; set; }
        public string cik { get; set; }
    }
}
