//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketValue
    {
        public int Id { get; set; }
        public string method { get; set; }
        public string symbol { get; set; }
        public string date { get; set; }
        public Nullable<decimal> open { get; set; }
        public Nullable<decimal> high { get; set; }
        public Nullable<decimal> low { get; set; }
        public Nullable<decimal> close { get; set; }
        public Nullable<int> volume { get; set; }
        public Nullable<decimal> uOpen { get; set; }
        public Nullable<decimal> uHigh { get; set; }
        public Nullable<decimal> uLow { get; set; }
        public Nullable<decimal> uClose { get; set; }
        public Nullable<int> uVolume { get; set; }
        public Nullable<decimal> change { get; set; }
        public Nullable<decimal> changePercent { get; set; }
        public string label { get; set; }
        public Nullable<decimal> changeOverTime { get; set; }
        public Nullable<System.DateTime> MarketTimestamp { get; set; }
    }
}
