//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_MARKET_DATA_STREAM
    {
        public string Symbol { get; set; }
        public Nullable<int> Interval { get; set; }
        public Nullable<bool> DONE { get; set; }
    }
}
