//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpTable
    {
        public int id { get; set; }
        public string method { get; set; }
        public string symbol { get; set; }
        public string companyName { get; set; }
        public string exchange { get; set; }
        public string industry { get; set; }
        public string website { get; set; }
        public string description { get; set; }
        public string CEO { get; set; }
        public string securityName { get; set; }
        public string issueType { get; set; }
        public string sector { get; set; }
        public Nullable<int> primarySicCode { get; set; }
        public Nullable<int> employees { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string date { get; set; }
        public Nullable<decimal> open { get; set; }
        public Nullable<decimal> high { get; set; }
        public Nullable<decimal> low { get; set; }
        public Nullable<decimal> close { get; set; }
        public Nullable<int> volume { get; set; }
        public Nullable<decimal> uOpen { get; set; }
        public Nullable<decimal> uHigh { get; set; }
        public Nullable<decimal> uLow { get; set; }
        public Nullable<decimal> uClose { get; set; }
        public Nullable<int> uVolume { get; set; }
        public Nullable<decimal> change { get; set; }
        public Nullable<decimal> changePercent { get; set; }
        public string label { get; set; }
        public Nullable<decimal> changeOverTime { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string iexId { get; set; }
        public string region { get; set; }
        public string currency { get; set; }
        public string isEnabled { get; set; }
        public string figi { get; set; }
        public string cik { get; set; }
        public string minute { get; set; }
        public string exDate { get; set; }
        public string paymentDate { get; set; }
        public string recordDate { get; set; }
        public string declaredDate { get; set; }
        public string amount { get; set; }
        public string flag { get; set; }
        public string frequency { get; set; }
        public string headline { get; set; }
        public string source { get; set; }
        public string url { get; set; }
        public string summary { get; set; }
        public string related { get; set; }
        public string image { get; set; }
        public string lang { get; set; }
        public string hasPaywall { get; set; }
        public Nullable<long> datetime { get; set; }
        public Nullable<decimal> iexClose { get; set; }
        public string primaryExchange { get; set; }
        public string calculationPrice { get; set; }
        public Nullable<long> openTime { get; set; }
        public string openSource { get; set; }
        public Nullable<long> closeTime { get; set; }
        public string closeSource { get; set; }
        public Nullable<long> highTime { get; set; }
        public string highSource { get; set; }
        public Nullable<long> lowTime { get; set; }
        public string lowSource { get; set; }
        public Nullable<decimal> latestPrice { get; set; }
        public string latestSource { get; set; }
        public string latestTime { get; set; }
        public Nullable<long> latestUpdate { get; set; }
        public Nullable<int> latestVolume { get; set; }
        public string iexRealtimePrice { get; set; }
        public string iexRealtimeSize { get; set; }
        public string iexLastUpdated { get; set; }
        public Nullable<decimal> delayedPrice { get; set; }
        public Nullable<long> delayedPriceTime { get; set; }
        public Nullable<decimal> oddLotDelayedPrice { get; set; }
        public Nullable<long> oddLotDelayedPriceTime { get; set; }
        public Nullable<decimal> extendedPrice { get; set; }
        public Nullable<decimal> extendedChange { get; set; }
        public Nullable<decimal> extendedChangePercent { get; set; }
        public Nullable<long> extendedPriceTime { get; set; }
        public Nullable<decimal> previousClose { get; set; }
        public Nullable<int> previousVolume { get; set; }
        public string iexMarketPercent { get; set; }
        public string iexVolume { get; set; }
        public Nullable<int> avgTotalVolume { get; set; }
        public string iexBidPrice { get; set; }
        public string iexBidSize { get; set; }
        public string iexAskPrice { get; set; }
        public string iexAskSize { get; set; }
        public string iexOpen { get; set; }
        public string iexOpenTime { get; set; }
        public Nullable<long> iexCloseTime { get; set; }
        public Nullable<long> marketCap { get; set; }
        public Nullable<decimal> peRatio { get; set; }
        public Nullable<decimal> week52High { get; set; }
        public Nullable<decimal> week52Low { get; set; }
        public Nullable<decimal> ytdChange { get; set; }
        public Nullable<long> lastTradeTime { get; set; }
        public string isUSMarketOpen { get; set; }
        public string sourceAPI { get; set; }
        public Nullable<decimal> adjClose { get; set; }
        public Nullable<decimal> unadjustedVolume { get; set; }
        public Nullable<decimal> vwap { get; set; }
    }
}
