//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DepotComponentsAggregated
    {
        public int DepotComponentId { get; set; }
        public int DepotId { get; set; }
        public string UserHK { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string Symbol { get; set; }
        public string Quantity { get; set; }
        public Nullable<decimal> PositionValueThen { get; set; }
        public Nullable<decimal> PositionValueNow { get; set; }
        public Nullable<decimal> PositionNetValue { get; set; }
        public Nullable<decimal> Percentage { get; set; }
    }
}
