//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MARKET_DATA_CLOSE_INTRADAY
    {
        public int ColumnID { get; set; }
        public string Symbol { get; set; }
        public Nullable<System.DateTime> Market_Timestamp { get; set; }
        public Nullable<decimal> Close { get; set; }
    }
}
