//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RUNNING_QUERIES
    {
        public string TEXT { get; set; }
        public short session_id { get; set; }
        public string status { get; set; }
        public string command { get; set; }
        public int cpu_time { get; set; }
        public int total_elapsed_time { get; set; }
    }
}
