//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SYMBOL
    {
        public int SymbolId { get; set; }
        public string Symbol { get; set; }
        public string CompanyName { get; set; }
        public string Industry { get; set; }
        public string Sector { get; set; }
        public string Website { get; set; }
        public string Description { get; set; }
        public string CEO { get; set; }
        public string SecurityName { get; set; }
        public string country { get; set; }
    }
}
