//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UserDepot
    {
        public Nullable<int> DepotId { get; set; }
        public string Symbol { get; set; }
        public string Company { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string UserName { get; set; }
        public string DepotName { get; set; }
        public string UserHK { get; set; }
        public string UserDepotHK { get; set; }
        public Nullable<System.DateTime> ComponentValidFrom { get; set; }
        public Nullable<System.DateTime> ComponentValidTo { get; set; }
        public Nullable<System.DateTime> DepotValidFrom { get; set; }
        public Nullable<System.DateTime> DepotValidTo { get; set; }
    }
}
