//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UserDepotAnalytics
    {
        public Nullable<int> DepotId { get; set; }
        public string Symbol { get; set; }
        public string Company { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Username { get; set; }
        public string DepotName { get; set; }
        public Nullable<decimal> close { get; set; }
        public Nullable<decimal> low { get; set; }
        public Nullable<decimal> open { get; set; }
        public Nullable<int> volume { get; set; }
        public Nullable<System.DateTime> ComponentValidFrom { get; set; }
        public Nullable<System.DateTime> ComponentValidTo { get; set; }
        public Nullable<System.DateTime> MarketTimestamp { get; set; }
    }
}
