//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWPFNetFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_FlowControl
    {
        public Nullable<int> AppID { get; set; }
        public string AppName { get; set; }
        public string Parameter { get; set; }
        public string TargetTable1 { get; set; }
        public int TaskSuccess { get; set; }
        public string TaskPlannedInterval { get; set; }
    }
}
