// <auto-generated />
using System;
using DataOperator.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ReportService.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20210208135717_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DataOperator.Models.Logs", b =>
                {
                    b.Property<int>("Log_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("ITS")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Log_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Logging_Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Machine_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Service_Step_Num")
                        .HasColumnType("int");

                    b.Property<int>("Solved")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int");

                    b.Property<int>("Thread_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("UTS")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("Log_Id");

                    b.ToTable("LOGS", "logging");
                });

            modelBuilder.Entity("DataOperator.Models.ReportConfiguration", b =>
                {
                    b.Property<string>("Report_Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Header_Row")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Report_Separator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Report_Sql")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Report_Name");

                    b.ToTable("V_Report_Overview", "reporting");
                });
#pragma warning restore 612, 618
        }
    }
}
