// <auto-generated />
using System;
using DataOperator.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ReportService.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20210131191004_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DataOperator.Models.Logs", b =>
                {
                    b.Property<string>("LogMessage")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("LogTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceMethod")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LogMessage", "LogTime", "ServiceId", "ServiceMethod");

                    b.ToTable("F_SERVICE_LOGS", "logging");
                });

            modelBuilder.Entity("DataOperator.Models.ReportConfiguration", b =>
                {
                    b.Property<string>("Report_Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Header_Row")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Report_Separator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Report_Sql")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Report_Name");

                    b.ToTable("V_Report_Overview", "reporting");
                });
#pragma warning restore 612, 618
        }
    }
}
